version: "2"
services:
  requisition:
    image: openlmis/requisition
    links:
      - db
      - log
    ports:
      - "8080"
    environment:
      - VIRTUAL_HOST=localhost
      - VIRTUAL_PORT=8080
    env_file: .env
  db:
    image: openlmis/postgres
    ports:
      - "5432"
    env_file: .env
  log:
    image: openlmis/rsyslog
    volumes:
      - '../logs/requisition:/var/log'
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    links:
      - requisition
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
