version: "2"
services:
  template:
    image: openlmis/dev
    links:
      - db
    volumes:
      - '.:/app'
    ports:
      - "8080:8080"
    command: 'clean build bootRun'
  db:
    image: openlmis/postgres
    ports:
      - "5432"
