version: "2"
services:
  requisition:
    image: openlmis/requisition
    links:
      - db
      - log
      - auth
      - nginx-proxy
    env_file: .env
    environment:
      - VIRTUAL_HOST=localhost
      - VIRTUAL_PORT=8080
  db:
    image: openlmis/postgres
    env_file: .env
  log:
    image: openlmis/rsyslog
    volumes:
      - '../logs/requisition:/var/log'
  auth:
    image: openlmis/auth
    ports:
    - "8081:8080"
    env_file: .env
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
