version: "2"
services:
  requisition:
    image: requisition
    links:
      - db
      - log
    ports:
      - "8080:8080"
  db:
    image: openlmis/postgres
    ports:
      - "5432"
  log:
    image: openlmis/rsyslog
    volumes:
      - '../logs/requisition:/var/log'
