version: "2"
services:

  requisition:
    image: openlmis/dev
    volumes:
      - '.:/app'
      - 'gradlecache:/gradle'
  db:
    ports:
      - "5432"

volumes:
  gradlecache:
    external: false
