version: "2"
services:
  requisition:
    image: openlmis/dev
    volumes:
      - '.:/app'
      - 'gradlecache:/gradle'
  requisition-build:
    image: openlmis/dev
    entrypoint:
      - 'gradle'
    command:
      - 'clean'
      - 'build'
    environment:
      GRADLE_OPTS: '-Dorg.gradle.daemon=false'
    volumes:
      - '.:/app'
      - 'gradlecache:/gradle'
volumes:
  gradlecache:
    external: false
